const filterMapping = {
    liquidityMin: "min_liquidity",
    liquidityMax: "max_liquidity",
    marketCapMin: "min_market_cap",
    marketCapMax: "max_market_cap",
    txns24hMin: "min_txns_24h",
    txns24hMax: "max_txns_24h",
    buys24hMin: "min_buys_24h",
    buys24hMax: "max_buys_24h",
    sells24hMin: "min_sells_24h",
    sells24hMax: "max_sells_24h",
    volume24hMin: "min_volume_24h",
    volume24hMax: "max_volume_24h",
    change24hMin: "min_change_24h",
    change24hMax: "max_change_24h",
    txns6hMin: "min_txns_6h",
    txns6hMax: "max_txns_6h",
    buys6hMin: "min_buys_6h",
    buys6hMax: "max_buys_6h",
    sells6hMin: "min_sells_6h",
    sells6hMax: "max_sells_6h",
    volume6hMin: "min_volume_6h",
    volume6hMax: "max_volume_6h",
    change6hMin: "min_change_6h",
    change6hMax: "max_change_6h",
    txns1hMin: "min_txns_1h",
    txns1hMax: "max_txns_1h",
    buys1hMin: "min_buys_1h",
    buys1hMax: "max_buys_1h",
    sells1hMin: "min_sells_1h",
    sells1hMax: "max_sells_1h",
    volume1hMin: "min_volume_1h",
    volume1hMax: "max_volume_1h",
    change1hMin: "min_change_1h",
    change1hMax: "max_change_1h",
    txns5mMin: "min_txns_5m",
    txns5mMax: "max_txns_5m",
    buys5mMin: "min_buys_5m",
    buys5mMax: "max_buys_5m",
    sells5mMin: "min_sells_5m",
    sells5mMax: "max_sells_5m",
    volume5mMin: "min_volume_5m",
    volume5mMax: "max_volume_5m",
    change5mMin: "min_change_5m",
    change5mMax: "max_change_5m",
  };
  
  export default filterMapping;
  